### -------------------------------------------------------------------------------------------------------------------

### Testing FastAPI Backend endpoints

### root
GET {{$dotenv PII_FASTAPI_BACKEND_URL}}

### health
GET {{$dotenv PII_FASTAPI_BACKEND_URL}}/health

### users - not authenticated
GET {{$dotenv PII_FASTAPI_BACKEND_URL}}/users

### users - authenticated with API key
GET {{$dotenv PII_FASTAPI_BACKEND_URL}}/users
Authorization: Bearer {{$dotenv PII_API_KEY}}

### user details - authenticated with API key
GET {{$dotenv PII_FASTAPI_BACKEND_URL}}/users/0306ce5a-f309-47b2-b490-5345a605ef24
Authorization: Bearer {{$dotenv PII_API_KEY}}

### create user - authenticated with API key
POST {{$dotenv PII_FASTAPI_BACKEND_URL}}/users
Authorization: Bearer {{$dotenv PII_API_KEY}}
Content-Type: application/json

{
    "email": "sarah.williams@demosite.net",
    "first_name": "Sarah",
    "last_name": "Williams",
    "phone": "3216549870",
    "address": "1247 Maple Drive, Denver, CO",
    "date_of_birth": "1988-11-03",
    "ip_address": null,
    "ssn": "456-78-9123",
    "bank_account": "1122334455",
    "credit_card": "3782-8224-6310-005"
}