[project]
name = "pii-encryption-lambda"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "boto3>=1.39.10",
    "cryptography>=45.0.5",
    "psycopg2-binary>=2.9.10",
]
